# Site settings
title: Joshua Dunbar
email: joshua_dunbar@me.com
description: > # this means to ignore newlines until "baseurl:"
Netlify is the best and this is my answers to their questions website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://friendly-meitner-c66d16.netlify.com" # the base hostname & protocol for your site
twitter_username: McPanda22
github_username: EngineeringPanda

# Build settings
markdown: kramdown
